### ISSUE TITLE
ImportError: `load_boston` has been removed from scikit-learn since version 1.2.

### ISSUE THREAD

**Issue by matmuttt** [amueller/introduction_to_ml_with_python#171]
Hello,
when I run this : 
```
import mglearn
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15), marker='o', hist_kwds={'bins': 20}, s=20, alpha = 8, cmap=mglearn.cm3)
```

I have an error in my terminal : 
ImportError:
`load_boston` has been removed from scikit-learn since version 1.2.

So I can't get the graphics of the fig 1.3 page 22 in the book... 

And i have also a problem when I import mglearn : 
Traceback (most recent call last):
  _File "f:/PROJECT/LIVRE/main.py", line 107, in <module>
    import mglearn
  File "C:\Users\starc\AppData\Local\Programs\Python\Python38\lib\site-packages\mglearn\__init__.py", line 1, in <module>
    from . import plots
  File "C:\Users\starc\AppData\Local\Programs\Python\Python38\lib\site-packages\mglearn\plots.py", line 5, in <module>
    from .plot_knn_regression import plot_knn_regression
  File "C:\Users\starc\AppData\Local\Programs\Python\Python38\lib\site-packages\mglearn\plot_knn_regression.py", line 7, in <module>
    from .datasets import make_wave
  File "C:\Users\starc\AppData\Local\Programs\Python\Python38\lib\site-packages\mglearn\datasets.py", line 5, in <module>
    from sklearn.datasets import load_boston
  File "C:\Users\starc\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\datasets\__init__.py", line 156, in __getattr__
    raise ImportError(msg)_

Hope you can help me !

**Comment by niall-byrne** [comment]
It's unfortunate about the racist data, but a quick workaround is to just heed the version warning:
> load_boston has been removed from scikit-learn since version 1.2.

`pip install "joblib<1.2"`

**Comment by BrayanMnz** [comment]
If you're using anaconda run this
`conda install scikit-learn=1.1.3`

and restart your kernel if you're using jupyter notebooks

**Comment by amueller** [comment]
If you update mglearn, this should be resolved now.
