### ISSUE TITLE
07-working-with-text-data.ipynb: ModuleNotFoundError: No module named 'spacy'

### ISSUE THREAD

**Issue by blinkeye** [amueller/introduction_to_ml_with_python#44]
On section _07-working-with-text-data.ipynb#Advanced-tokenization,-stemming-and-lemmatization_ I get the following error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-42-2aa020095bf1> in <module>()
----> 1 import spacy
      2 import nltk
      3 
      4 # load spacy's English-language models
      5 en_nlp = spacy.load('en')

ModuleNotFoundError: No module named 'spacy'
```
once I installed **spacy**:
```
$ conda install spacy
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/blinkeye/anaconda3:

The following NEW packages will be INSTALLED:

    cymem:      1.31.2-py36_0 
    murmurhash: 0.26.4-py36_0 
    plac:       0.9.6-py36_0  
    preshed:    0.46.4-py36_0 
    semver:     2.7.7-py36_0  
    spacy:      0.101.0-py36_0
    sputnik:    0.9.3-py36_0  
    thinc:      5.0.8-py36_0  
    ujson:      1.35-py36_0   

The following packages will be UPDATED:

    conda:      4.3.21-py36_0  --> 4.3.22-py36_0

Proceed ([y]/n)? y

```

I got further errors:

```
---------------------------------------------------------------------------
PackageNotFoundException                  Traceback (most recent call last)
/home/blinkeye/anaconda3/lib/python3.6/site-packages/spacy/util.py in get_package_by_name(name, via)
     43         return sputnik.package(about.__title__, about.__version__,
---> 44             name, data_path=via)
     45     except PackageNotFoundException as e:

/home/blinkeye/anaconda3/lib/python3.6/site-packages/sputnik/__init__.py in package(app_name, app_version, package_string, data_path)
    159     pool = Pool(app_name, app_version, expand_path(data_path))
--> 160     return pool.get(package_string)
    161 

/home/blinkeye/anaconda3/lib/python3.6/site-packages/sputnik/package_list.py in get(self, package_string)
     56         if not candidates:
---> 57             raise PackageNotFoundException(package_string)
     58 

PackageNotFoundException: en
```

Then I followed [conda-forge / packages / spacy 1.8.2](https://anaconda.org/conda-forge/spacy)

```
$ conda install -c conda-forge spacy=1.8.2
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/blinkeye/anaconda3:

The following NEW packages will be INSTALLED:

    ftfy:      4.4.2-py36_0      conda-forge
    regex:     2017.04.05-py36_0 conda-forge
    termcolor: 1.1.0-py36_1      conda-forge
    tqdm:      4.14.0-py36_0     conda-forge

The following packages will be UPDATED:

    preshed:   0.46.4-py36_0                 --> 1.0.0-py36_0      conda-forge
    spacy:     0.101.0-py36_0                --> 1.8.2-np112py36_0 conda-forge
    thinc:     5.0.8-py36_0                  --> 6.5.2-np112py36_0 conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:     4.3.22-py36_0                 --> 4.3.21-py36_1     conda-forge
    conda-env: 2.6.0-0                       --> 2.6.0-0           conda-forge

Proceed ([y]/n)? y
```
which seems to work (I still see a warning):

```
    Warning: no model found for 'en'

    Only loading the 'en' tokenizer.
```

**Comment by blinkeye** [comment]
Do you want another PR for updating the README with the above conda spacy instructions?

**Comment by amueller** [comment]
I'm confused by the instructions.
You need to ``conda install spacy``
Then spacy should tell you to run
``python -m spacy download en`` to download the en models.
Happy to have a note in the REAME about running that second command. Isn't that mentioned in the error message you get?

**Comment by blinkeye** [comment]
Thanks. I tried your instructions and removed the spacy-1.8.2 from above again.
However, with my current up-to-date anaconda version and environment this does not work.

I've installed the default spacy version which seems to be 0.101.0:

```
$ conda install spacy
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment ~/anaconda3:

The following NEW packages will be INSTALLED:

    spacy:     0.101.0-py36_0               

The following packages will be UPDATED:

    conda:     4.3.21-py36_1     conda-forge --> 4.3.22-py36_0

The following packages will be SUPERSEDED by a higher-priority channel:

    conda-env: 2.6.0-0           conda-forge --> 2.6.0-0      
    preshed:   1.0.0-py36_0      conda-forge --> 0.46.4-py36_0
    thinc:     6.5.2-np112py36_0 conda-forge --> 5.0.8-py36_0 

Proceed ([y]/n)? y

conda-env-2.6. 100% |#####################################################################################################################################################################################################################################| Time: 0:00:00 858.00 kB/s

```

There's no info about running:
```
$ python -m spacy download en
```
Still, the above command would not work since that calls the platform standard python environment - not the conda python environment. So I executed :
```
$  ~/anaconda3/bin/python  -m spacy download en
```
which gives me:
`  ~/anaconda3/bin/python: No module named spacy.__main__; 'spacy' is a package and cannot be directly executed`

**Comment by blinkeye** [comment]
Next I followed [these instructions](https://spacy.io/docs/usage/) and added the **conda-forge channel**:

```
$ conda config --add channels conda-forge
```
Next I installed spacy again:
```
$ conda install spacy
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment ~anaconda3:

The following NEW packages will be INSTALLED:

    spacy:     1.8.2-np112py36_0 conda-forge

The following packages will be UPDATED:

    preshed:   0.46.4-py36_0                 --> 1.0.0-py36_0      conda-forge
    thinc:     5.0.8-py36_0                  --> 6.5.2-np112py36_0 conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:     4.3.22-py36_0                 --> 4.3.21-py36_1     conda-forge
    conda-env: 2.6.0-0                       --> 2.6.0-0           conda-forge

Proceed ([y]/n)? 
```
and that seems to work. No info about downloaded some packages, but now the spacy download command works:

```
~/anaconda3/bin/python  -m spacy download en

    Downloading en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz

Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz (52.2MB)
    100% |████████████████████████████████| 52.2MB 3.5MB/s 
Requirement already satisfied: spacy<2.0.0,>=1.7.0 in ./anaconda3/lib/python3.6/site-packages (from en-core-web-sm==1.2.0)
Requirement already satisfied: numpy>=1.7 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: murmurhash<0.27,>=0.26 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: cymem<1.32,>=1.30 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: thinc<6.6.0,>=6.5.0 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Collecting pathlib (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 1.0MB/s 
Requirement already satisfied: ujson>=1.35 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: dill<0.3,>=0.2 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: regex==2017.4.5 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: ftfy<5.0.0,>=4.4.2 in ./anaconda3/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: wrapt in ./anaconda3/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in ./anaconda3/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: cytoolz<0.9,>=0.8 in ./anaconda3/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: termcolor in ./anaconda3/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: html5lib in ./anaconda3/lib/python3.6/site-packages (from ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.6/site-packages (from ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Installing collected packages: en-core-web-sm, pathlib
  Running setup.py install for en-core-web-sm ... done
  Running setup.py install for pathlib ... done
Successfully installed en-core-web-sm-1.2.0 pathlib-1.0.1

    Linking successful

    /home/blinkeye/anaconda3/lib/python3.6/site-packages/en_core_web_sm/en_core_web_sm-1.2.0
    --> /home/blinkeye/anaconda3/lib/python3.6/site-packages/spacy/data/en

    You can now load the model via spacy.load('en').
```

**Comment by amueller** [comment]
That sounds like a bug in the conda packaging?

**Comment by amueller** [comment]
> Still, the above command would not work since that calls the platform standard python environment - not the conda python environment. So I executed :

Wait a minute, ``python`` should point to ``anaconda3/bin/python`` or all bets are off. You should either create a conda environment and activate it or add ``anaconda3/bin`` to your ``PATH`` as you were instructed when installing conda.

**Comment by amueller** [comment]
But it also looks like the conda main spacy package is out of date, right?

**Comment by blinkeye** [comment]
> But it also looks like the conda main spacy package is out of date, right?

Yes, that's what I think. Still, the [Anaconda Spacy Info Page](https://anaconda.org/spacy/spacy) list the 0.101.0 version, so this might be on purpose.

I checked the [github spaCy project](https://github.com/explosion/spaCy/tags) which clearly shows that **1.8.2** is the current release version.

So, back to the reason why I opened this issue: in the _README.md_ there's no indication of the spaCy dependency. Don't you think it would help adding my suggested spaCy instructions above? Since the default anaconda spaCy version is wrong I think some users might struggle to get  _07-working-with-text-data.ipynb_ running (as I did).

**Comment by amueller** [comment]
Yes, a PR that adds to the readme that for part of 07 you need spacy and how to install it from conda-forge would be good. Not sure if pipy might be a better option, though?

**Comment by blinkeye** [comment]
I'll add instructions for both, and add the link to [spaCy ](https://spacy.io/docs/usage/)

**Comment by blinkeye** [comment]
FYI: I tried installing spacy with pip in a fresh anaconda 4.4.0 environment (actually using the official [ContinuumIO/anaconda docker image](https://github.com/ContinuumIO/docker-images/tree/master/anaconda)) and failed.

Appart from the fact quite a few packages have to be built (and require gcc, g++ and co., in debian terms the package _build-essential_):
```
Collecting spacy
  Downloading spacy-1.8.2.tar.gz (3.3MB)
Requirement already satisfied: numpy>=1.7 in /opt/conda/lib/python2.7/site-packages (from spacy)
Collecting murmurhash<0.27,>=0.26 (from spacy)
  Downloading murmurhash-0.26.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cymem<1.32,>=1.30 (from spacy)
  Downloading cymem-1.31.2-cp27-cp27mu-manylinux1_x86_64.whl (66kB)
Collecting preshed<2.0.0,>=1.0.0 (from spacy)
  Downloading preshed-1.0.0.tar.gz (89kB)
Collecting thinc<6.6.0,>=6.5.0 (from spacy)
  Downloading thinc-6.5.2.tar.gz (926kB)
Collecting plac<1.0.0,>=0.9.6 (from spacy)
  Downloading plac-0.9.6-py2.py3-none-any.whl
Requirement already satisfied: six in /opt/conda/lib/python2.7/site-packages (from spacy)
Collecting pathlib (from spacy)
  Downloading pathlib-1.0.1.tar.gz (49kB)
Collecting ujson>=1.35 (from spacy)
  Downloading ujson-1.35.tar.gz (192kB)
Collecting dill<0.3,>=0.2 (from spacy)
  Downloading dill-0.2.6.zip (83kB)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/conda/lib/python2.7/site-packages (from spacy)
Collecting regex==2017.4.5 (from spacy)
  Downloading regex-2017.04.05.tar.gz (601kB)
Collecting ftfy<5.0.0,>=4.4.2 (from spacy)
  Downloading ftfy-4.4.3.tar.gz (50kB)
Requirement already satisfied: wrapt in /opt/conda/lib/python2.7/site-packages (from thinc<6.6.0,>=6.5.0->spacy)
Collecting tqdm<5.0.0,>=4.10.0 (from thinc<6.6.0,>=6.5.0->spacy)
  Downloading tqdm-4.14.0-py2.py3-none-any.whl (46kB)
Requirement already satisfied: cytoolz<0.9,>=0.8 in /opt/conda/lib/python2.7/site-packages (from thinc<6.6.0,>=6.5.0->spacy)
Collecting termcolor (from thinc<6.6.0,>=6.5.0->spacy)
  Downloading termcolor-1.1.0.tar.gz
Requirement already satisfied: html5lib in /opt/conda/lib/python2.7/site-packages (from ftfy<5.0.0,>=4.4.2->spacy)
Requirement already satisfied: wcwidth in /opt/conda/lib/python2.7/site-packages (from ftfy<5.0.0,>=4.4.2->spacy)
Building wheels for collected packages: spacy, preshed, thinc, pathlib, ujson, dill, regex, ftfy, termcolor
```
the built spacy module fails when executing:
```
$ python -m spacy download en

Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/opt/conda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/opt/conda/lib/python2.7/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/opt/conda/lib/python2.7/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/opt/conda/lib/python2.7/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/opt/conda/lib/python2.7/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/opt/conda/lib/python2.7/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
  File "spacy/morphology.pxd", line 25, in init spacy.gold (spacy/gold.cpp:23505)
  File "spacy/vocab.pxd", line 27, in init spacy.morphology (spacy/morphology.cpp:10713)
  File "spacy/serialize/packer.pxd", line 4, in init spacy.vocab (spacy/vocab.cpp:19480)
  File "spacy/serialize/huffman.pxd", line 15, in init spacy.serialize.packer (spacy/serialize/packer.cpp:23938)
ImportError: /opt/conda/lib/python2.7/site-packages/spacy/serialize/huffman.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
```
This is a similor error as in [spaCy: Import Error with version 1.6.0 #855](https://github.com/explosion/spaCy/issues/855).

I recommend (as mentioned in the above bug report) to use conda and get a pre-built spaCy package.

**Comment by amueller** [comment]
That's pretty weird. You really shouldn't need to build wheels for that many packages. It might be that that is caused by spacy pinning the versions very tightly? Maybe bring that up as an issue to them?

**Comment by vbabenko** [comment]
any updates on this?

**Comment by byorxyz** [comment]
I'm getting similar error as well.

```
[(san) aerin@aerin-HP-Z230-Tower-Workstation:~/Desktop/san_mrc$ python -m spacy download en
Traceback (most recent call last):
  File "/home/aerin/anaconda3/envs/san/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/aerin/anaconda3/envs/san/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/aerin/anaconda3/envs/san/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.5/dist-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/usr/local/lib/python3.5/dist-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/usr/local/lib/python3.5/dist-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/usr/local/lib/python3.5/dist-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/usr/local/lib/python3.5/dist-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ModuleNotFoundError: No module named 'spacy.gold'](url)
```

**Comment by amueller** [comment]
@byorxyz That looks like an unrelated error, maybe check the spacy issue tracker?
@vbabenko update on what?

**Comment by nush12** [comment]
I had a similar issue, due to multiple version of Pythons. I removed the older versions from PATH variable and ran the command as an **administrator.** Remember to run the command as an admin if not, the package may be downloaded, but a link won't be established due to access restrictions. In windows start -> cmd -> right click -> run as administrator

**python -m spacy download en**
