### ISSUE TITLE
I couldn't able to install mglearn using pip

### ISSUE THREAD

**Issue by vamshigunji183** [amueller/introduction_to_ml_with_python#71]
is there any proper way to install mglearn?

**Comment by amueller** [comment]
``pip install mglearn``.

**Comment by vamshigunji183** [comment]
This is the error ..



C:\Users\gvvam>pip install mglearn
Collecting mglearn
Exception:
Traceback (most recent call last):
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\gvvam\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

**Comment by amueller** [comment]
And in the issue you posted about it I gave you the solution, which is unrelated to mglearn really.

**Comment by amueller** [comment]
@TanCha96 check http://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by vamshigunji183** [comment]
Are you trying to run in anaconda
Even I have faced similar problem
Conda install pip
Pip install mglearn

**Comment by jouellnyc** [comment]
@vamshigunji183 Yes, your solution works, thanks for that.
